name: C API for V8 monolithic static library
on:
   [push]
#  release:
#    types:
#      - published

env:
  V8_VERSION: '15.2.124.4'

defaults:
  run:
    shell: bash

jobs:
  build-on-linux-aarch64:
    runs-on: ubuntu-22.04-arm
    env:
      V8_OS: linux
      V8_ARCH: aarch64
    steps:
      - name: Source code checkout
        uses: actions/checkout@v7
        with:
          path: ${{ github.event.repository.name }}
      - name: V8 fetch and build
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export DEPOT_TOOLS_METRICS=0
          export PATH="$PATH:$HOME/.cargo/env:$GITHUB_WORKSPACE/depot_tools"
          gclient
          fetch v8
          cd $GITHUB_WORKSPACE/v8
          git checkout $V8_VERSION
          gclient sync
          mkdir "build-$V8_OS-$V8_ARCH"
          cp "../${{ github.event.repository.name }}/$V8_OS-$V8_ARCH.gn" "build-$V8_OS-$V8_ARCH/args.gn"
          gn gen "build-$V8_OS-$V8_ARCH" --args='rust_sysroot_absolute="$HOME/.rustup/toolchains/stable-aarch64-unknown-linux-gnu"'
          ninja -j 4 v8_monolith -C "build-$V8_OS-$V8_ARCH"
      - name: V8 logs
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"
          cd $GITHUB_WORKSPACE/v8
          echo "----------------- os-release      -----------------"
          cat /etc/os-release
          echo "----------------- uname           -----------------"
          uname -a
          echo "----------------- clang version   -----------------"
          third_party/llvm-build/Release+Asserts/bin/clang -v
          echo "----------------- sysroots.json   -----------------"
          cat build/linux/sysroot_scripts/sysroots.json
          echo "----------------- gn args list    -----------------"
          gn args "build-$V8_OS-$V8_ARCH" --list
          echo "----------------- gn ls //:*      -----------------"
          gn ls "build-$V8_OS-$V8_ARCH" //:*
          echo "----------------- gn desc         -----------------"
          gn desc "build-$V8_OS-$V8_ARCH" //:v8_monolith
          echo "----------------- find *libc++*.a -----------------"
          find "build-$V8_OS-$V8_ARCH" -name "*libc++*.a"
