name: C API for V8 monolithic static library
on:
   [push]
#  release:
#    types:
#      - published

env:
  V8_VERSION: '15.2.124.4'

defaults:
  run:
    shell: bash

jobs:
  build-on-linux-aarch64:
    runs-on: ubuntu-22.04-arm
    env:
      V8_OS: linux
      V8_ARCH: aarch64
    steps:
      - name: Source code checkout
        uses: actions/checkout@v7
        with:
          path: ${{ github.event.repository.name }}
      - name: V8 fetch and build
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.0/LLVM-22.1.0-Linux-ARM64.tar.xz
          mkdir llvm-aarch64
          tar -xvf LLVM-22.1.0-Linux-ARM64.tar.xz -C ./llvm-aarch64 --strip-components=1
          ./llvm-aarch64/bin/clang --version
