name: C API for V8 monolithic static library
on:
   [push]
#  release:
#    types:
#      - published

env:
  V8_VERSION: '15.2.124.4'

defaults:
  run:
    shell: bash

jobs:
  build-on-linux-aarch64:
    runs-on: ubuntu-22.04-arm
    env:
      V8_OS: linux
      V8_ARCH: aarch64
    steps:
      - name: Source code checkout
        uses: actions/checkout@v7
        with:
          path: ${{ github.event.repository.name }}
      - name: V8 fetch and build
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 23 all
          /usr/lib/llvm-23/bin/clang -v
          find /usr/lib/llvm-23 "libclang_rt.builtins.a"
